// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC75cPG9g0xCogxyh4FKgUWZ68ge5JCwec',
    appId: '1:523662016575:web:f35ed906250bae9747388a',
    messagingSenderId: '523662016575',
    projectId: 'codemaster-pro-8417c',
    authDomain: 'codemaster-pro-8417c.firebaseapp.com',
    storageBucket: 'codemaster-pro-8417c.firebasestorage.app',
    measurementId: 'G-3HXRN5WM2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTOVenM5nUGfi-3bV8or4h83fiz1BHImA',
    appId: '1:523662016575:android:0baa90eeb38e3f4547388a',
    messagingSenderId: '523662016575',
    projectId: 'codemaster-pro-8417c',
    storageBucket: 'codemaster-pro-8417c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkJpJQLywbU-digM4XdMBtZgyyTI1V3N4',
    appId: '1:523662016575:ios:90def02fdd3e7d9947388a',
    messagingSenderId: '523662016575',
    projectId: 'codemaster-pro-8417c',
    storageBucket: 'codemaster-pro-8417c.firebasestorage.app',
    iosBundleId: 'com.codemaster.codemasterPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkJpJQLywbU-digM4XdMBtZgyyTI1V3N4',
    appId: '1:523662016575:ios:90def02fdd3e7d9947388a',
    messagingSenderId: '523662016575',
    projectId: 'codemaster-pro-8417c',
    storageBucket: 'codemaster-pro-8417c.firebasestorage.app',
    iosBundleId: 'com.codemaster.codemasterPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC75cPG9g0xCogxyh4FKgUWZ68ge5JCwec',
    appId: '1:523662016575:web:339c3381886cb82647388a',
    messagingSenderId: '523662016575',
    projectId: 'codemaster-pro-8417c',
    authDomain: 'codemaster-pro-8417c.firebaseapp.com',
    storageBucket: 'codemaster-pro-8417c.firebasestorage.app',
    measurementId: 'G-LL8YJKQ9PS',
  );
}
